### ISSUE TITLE
Standalone comical-js samples

### ISSUE THREAD

**Issue by alp-test** [BloomBooks/comical-js#89]
I would like to try out comical-js for a prototype I am trying to create to incorporate speech bubbles in my web content. Seems like comical-js can do what I am looking for based on the description. I am looking for a way to run some standalone samples along with it's source code to get an idea how to use the library. I looked at the github readme.md but couldn't quite follow. I see this step in the Developing section: 

"Do this to launch a browser window in which you can see various examples of ComicalJS running, or add your own yarn storybook"

Which I thought will enable me to checkout some samples. But I get the following: 

$ yarn storybook
yarn run v1.22.10
warning package.json: No license field
error Command "storybook" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is the first time I have used yarn, so don't know if I am missing some step or missing something in the package.json. I haven't really started developing anything with comical-js so don't know if I am supposed to configure yarn or my project before being able to run those samples. Any pointers would be greatly appreciated.

**Comment by andrew-polk** [comment]
Are you sure you're running `yarn storybook` in the root directory of the comical-js repository after you clone it?
The `package.json` for comical-js does have a license field, and it does define a `storybook` script.

**Comment by alp-test** [comment]
Thank you, that worked.

**Comment by kogratte** [comment]
Hello guys.

Reup for this one, as it seems that... This lib is not working anymore :)

When using the indicated commands, I just got an ssl error, and can't move away from it.
```sh
info => Loading custom Webpack config (full-control mode).
10% building 1/4 modules 3 active ...ybook/core/dist/server/common/polyfills.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
```

Is an update available somewhere? Should I just run away?

**Comment by andrew-polk** [comment]
Looks like you need to use node 16.
Our team uses volta, and I've added that directive in the package.json.
If you don't use volta, you'll need to specify node 16 manually.
Note that this package still uses yarn 1.
